### ISSUE TITLE
导出excel临时文件的存放位置相关问题

### ISSUE THREAD

**Issue by zhangmrit** [zhangmrit/ruoyi-cloud#6]
在若依中是存到本地磁盘的，但是在微服务中不可取，各自服务间无法相互调用
有解决方案的可以在下方评论

**Comment by zhangmrit** [comment]
有可能需要改变模式，直接流输出

**Comment by fuhuarenshi** [comment]
有过解决方法，好像是存放到本地然后，上传到oss，然后删除本地的文件。

**Comment by fuhuarenshi** [comment]
删除本地文件是根据场景情况大小 跑的定时删除，删除整个文件夹

**Comment by zhangmrit** [comment]
> 有过解决方法，好像是存放到本地然后，上传到oss，然后删除本地的文件。

有点鸡肋啊

**Comment by fuhuarenshi** [comment]
> > 有过解决方法，好像是存放到本地然后，上传到oss，然后删除本地的文件。
> 
> 有点鸡肋啊

我们当时没用这个 ，用的是流输出，不过若依的生成excel模板可能没用上。看你数据要不要保留。不保留是流输出比较好，要到时候生成。保留的可能要上传到oss。
