### ISSUE TITLE
项目开启多页签模式，页面切换时页面的初始化问题

### ISSUE THREAD

**Issue by wwwJXwww** [zhangmrit/ruoyi-cloud#9]
![`9K6~ B{RU2I$5YPOE8XS_D](https://user-images.githubusercontent.com/44359100/70290778-f3af0400-1813-11ea-92ba-21e7614a8f3e.png)
![JBSMST`1J 5~WHIV{QEN$3](https://user-images.githubusercontent.com/44359100/70290792-01648980-1814-11ea-86ae-bb4d9c3be996.png)

**Comment by zhangmrit** [comment]
自己加个监听吧
